name:                http-lesson
version:             0.1.0.0
github:              "Rhywun/http-lesson"
license:             BSD3
author:              "Patrick Huffer"
maintainer:          "rhywun@rhywun.com"
copyright:           "Patrick Huffer"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/Rhywun/http-lesson#readme>

default-extensions:
- OverloadedStrings

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  http-lesson-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - http-lesson
    - bytestring
    - http-conduit
    - http-types

tests:
  http-lesson-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - http-lesson
